name: leetcode-python

on:
  push:
    branches: [ master ]
    paths:
      - 'leetcode-python/**'

  pull_request:
    branches: [ master ]
    paths:
      - 'leetcode-python/**'

jobs:
  build:
    name: pytest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      working-directory: ${{github.workspace}}/leetcode-python
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test with pytest
      run: |
        pytest . --verbose --cov --cov-report=term --cov-report=html
