name: leetcode-c

on:
  push:
    branches: [ master ]
    paths:
      - 'leetcode-c/**'

  pull_request:
    branches: [ master ]
    paths:
      - 'leetcode-c/**'

env:
  BUILD_TYPE: Debug

jobs:
  cmake-build-debug-linux-gcc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Configure CMake
      working-directory: ${{github.workspace}}/leetcode-c
      run: |
        cmake --version
        cmake -B ${{github.workspace}}/leetcode-c/cmake-build-debug -DCMAKE_BUILD_TYPE=Debug

    - name: Build
      run: cmake --build ${{github.workspace}}/leetcode-c/cmake-build-debug

    - name: Test
      working-directory: ${{github.workspace}}/leetcode-c/cmake-build-debug
      run: ctest --verbose

  cmake-build-release-linux-gcc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Configure CMake
      working-directory: ${{github.workspace}}/leetcode-c
      run: |
        cmake --version
        cmake -B ${{github.workspace}}/leetcode-c/cmake-build-release -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build ${{github.workspace}}/leetcode-c/cmake-build-release

    - name: Test
      working-directory: ${{github.workspace}}/leetcode-c/cmake-build-release
      run: ctest --verbose

  cmake-build-debug-macos-appleclang:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2

    - name: Configure CMake
      working-directory: ${{github.workspace}}/leetcode-c
      run: |
        cmake --version
        cmake -B ${{github.workspace}}/leetcode-c/cmake-build-debug -DCMAKE_BUILD_TYPE=Debug

    - name: Build
      run: cmake --build ${{github.workspace}}/leetcode-c/cmake-build-debug

    - name: Test
      working-directory: ${{github.workspace}}/leetcode-c/cmake-build-debug
      run: ctest --verbose

  cmake-build-release-macos-appleclang:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2

    - name: Configure CMake
      working-directory: ${{github.workspace}}/leetcode-c
      run: |
        cmake --version
        cmake -B ${{github.workspace}}/leetcode-c/cmake-build-release -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build ${{github.workspace}}/leetcode-c/cmake-build-release

    - name: Test
      working-directory: ${{github.workspace}}/leetcode-c/cmake-build-release
      run: ctest --verbose

  cmake-build-debug-windows-msvc:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v2

    - name: Get latest CMake
      # VS自带cmake存在ASan链接问题，启用第三方cmake
      uses: lukka/get-cmake@latest
     
    - name: Configure CMake
      working-directory: ${{github.workspace}}/leetcode-c
      run: |
        cmake --version
        cmake -B ${{github.workspace}}/leetcode-c/cmake-build-debug -DCMAKE_BUILD_TYPE=Debug

    - name: Build
      run: cmake --build ${{github.workspace}}/leetcode-c/cmake-build-debug

    - name: Test
      working-directory: ${{github.workspace}}/leetcode-c/cmake-build-debug
      run: ctest --verbose

  cmake-build-release-windows-msvc:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v2

    - name: Get latest CMake
      # VS自带cmake存在ASan链接问题，启用第三方cmake
      uses: lukka/get-cmake@latest
      
    - name: Configure CMake
      working-directory: ${{github.workspace}}/leetcode-c
      run: |
        cmake --version
        cmake -B ${{github.workspace}}/leetcode-c/cmake-build-release -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build ${{github.workspace}}/leetcode-c/cmake-build-release

    - name: Test
      working-directory: ${{github.workspace}}/leetcode-c/cmake-build-release
      run: ctest --verbose
